### ISSUE TITLE
remove color codes when sending from irc to slack

### ISSUE THREAD

**Issue by gnowxilef** [ocf/slackbridge#1]
and/or maybe even have an option to toggle it on/off?

**Comment by jvperrin** [comment]
Ah thanks, good idea, I think just removing the color codes would be best. It would be nice if Slack supported color codes in the first place, but of course it doesn't.

**Comment by nattofriends** [comment]
Slack supports bold and italic though

**Comment by jvperrin** [comment]
True, so maybe those could be converted instead of stripped, good point.

**Comment by gnowxilef** [comment]
i say medium-prio since it gets kind of annoying to read terrible color things in slack.

**Comment by jvperrin** [comment]
Sure, sounds good, it is pretty annoying
