### ISSUE TITLE
Ensure messages end up in the correct order when mirrored

### ISSUE THREAD

**Issue by jvperrin** [ocf/slackbridge#11]
If messages are posted very close to each other and have varying latency, then they can end up in the wrong order when mirrored. This happens more for messages from IRC -> Slack, but can also possibly happen in the other direction.

**Comment by gnowxilef** [comment]
yes please. why does that happen?

**Comment by jvperrin** [comment]
@gnowxilef This is because separate requests are sent for each message to Slack, so if the second one just happens to be faster (especially when `create` posts messages since it can post much quicker than actual humans can), then it will show up in the wrong order on Slack.

Messages going from Slack -> IRC are less likely to encounter this because they are pulled one by one from the [Slack RTM API](https://api.slack.com/rtm), so they should be in order, but delays of a second or so  in one request could still make this happen. It's probably only worth worrying about the IRC -> Slack ordering problem, since it's much more common.

**Comment by jvperrin** [comment]
This hasn't happened in a while, so I'm closing it. I think #35 fixed it (or it was fixed before potentially?)
