### ISSUE TITLE
Mirror private messages

### ISSUE THREAD

**Issue by jvperrin** [ocf/slackbridge#12]
Only channels are mirrored currently, and it would be nice to mirror private messages too. This would be tough, but could be done by someone messaging the user's IRC bot and then having that show up from the `irc-bridge` user in Slack with the original user's name in front of it. Then, when replying, you'd have to put that user's name in front in your message and it would get sent back to the right conversation. Not great, but better than people in IRC trying to message Slack users and the messages getting lost when the bridge doesn't send them on.

**Comment by kkuehler** [comment]
I'd prefer if instead you msg the bridge once to start a me
```
Me: start message jvperrin
Bridge: Okay, starting message with jvperrin
...
...
Me: end message jvperrin
Bridge: Okay, no longer messaging jvperrin
```

**Comment by jvperrin** [comment]
Yeah, that's definitely nicer, but it does mean that the bot has to keep some state, even when it restarts for instance.
