### ISSUE TITLE
Bridge usernames typed in chat correctly from Slack -> IRC

### ISSUE THREAD

**Issue by jvperrin** [ocf/slackbridge#15]
Currently they look something like `<@U6PNO549P>` when they should be `@user` instead.

**Comment by jvperrin** [comment]
The part about linking to channels and users in the [message formatting docs](https://api.slack.com/docs/message-formatting#linking_to_channels_and_users) is relevant here.

**Comment by matthew-mcallister** [comment]
Shouldn't it just be `user`, not `@user`?

**Comment by jvperrin** [comment]
Yeah, good point, they should be, part of this is making usernames from IRC have an @ in front on Slack though, so that would be nice too.

**Comment by kkuehler** [comment]
It's been a few days since #33 was merged with no issue so I'm closing this
