### ISSUE TITLE
slack-bridge sometimes doesn't join #rebuild

### ISSUE THREAD

**Issue by redplanks** [ocf/slackbridge#38]
And there don't seem to be any logs on it.

**Comment by jvperrin** [comment]
Same sometimes with #test, I think it likely happens with all channels?

**Comment by jvperrin** [comment]
I believe this should be fixed by some IRCd config tuning (in https://github.com/ocf/puppet/commit/3747542768a982f55ef4b963cd4f6edc1ef160a8 and https://github.com/ocf/puppet/commit/f9f49913189ed76769dbf65bc6f216271a2719c9), but we'll have to wait and see if it happens again.

**Comment by jvperrin** [comment]
I'll close this for now, and we can re-open it if it continues to be an issue.
