### ISSUE TITLE
Create a new IRC bot when a new user joins Slack

### ISSUE THREAD

**Issue by jvperrin** [ocf/slackbridge#4]
Currently they would not be able to talk from Slack -> IRC until the bridge restarts.

There is an [API method for when a new user joins Slack](https://api.slack.com/events/team_join), and messages are also sent when a user joins/quits a channel (with subtypes of `channel_join` and `channel_leave`), so we should be able to hook into those.

**Comment by kkuehler** [comment]
Fixed in https://github.com/ocf/slackbridge/pull/34
