### ISSUE TITLE
Determine why Slack -> IRC mirror sometimes stops

### ISSUE THREAD

**Issue by kkuehler** [ocf/slackbridge#43]
The consensus right now is to add a debug flag (command line arg) that toggles extensive logging. With that, we should be able to determine what is causing the IRC bots to suddenly stop mirroring Slack messages. Right now, we only see Slack events *before* they enter the queue. We probably want to log IRC bot messages before they are sent, when events enter the queue, when events are retrieved from the queue, queue size, etc. Finding the point of failure should hopefully be straightforward.

This will also set a good logging precedent for the future.

**Comment by gnowxilef** [comment]
+1

**Comment by jvperrin** [comment]
We haven't had this in ages, I think because we now [handle reconnection](https://github.com/ocf/slackbridge/commit/8cc430f737b61f7069e0351b1f7b96be0c0a6f66) properly? Anyway, adding more logging is definitely a good idea, but I think this can be closed for now.
