### ISSUE TITLE
Remove -xmpp suffixes from nicks

### ISSUE THREAD

**Issue by dkess** [ocf/slackbridge#75]
Since some people are using XMPP to connect to IRC now, they're using `nick-xmpp` names as their IRC nicks (note that this is only a convention-- XMPP users can actually pick any nick they'd like). Slcak users probably don't care about this, so we should strip `-xmpp` from nicks.

**Comment by jvperrin** [comment]
Meh, I feel like the added complexity and potential confusion here isn't really worth it, but if you think it would be worth doing then go for it.

**Comment by nattofriends** [comment]
How would this interact with private message bridging?

**Comment by dkess** [comment]
o yea I guess it would break that, I guess this won't work :(
