### ISSUE TITLE
Don't update channel topic when slackbridge restarts

### ISSUE THREAD

**Issue by jvperrin** [ocf/slackbridge#99]
The channel topic (on Slack anyway) always gets updated when slackbridge restarts, even if it doesn't need to be. We should stop that from happening ideally.

**Comment by ja5087** [comment]
Is this still an issue? #82

**Comment by jvperrin** [comment]
I think so? I believe I saw some topic updating recently even though I didn't think it needed to. Trying to run a dev version of the bridge or just restarting the prod bridge should show if it's actually an issue or not though.

**Comment by jvperrin** [comment]
Looks like that was back on the 2nd during the inspircd v3 upgrade you did, so maybe it's only when inspircd restarts from under the bridge. Probably not a bit deal, I'll close this and it can be reopened or a new issue made if it's an issue in the future.
